### ISSUE TITLE
Support UraniumX (URX)

### ISSUE THREAD

**Issue by axetota** [bogdanadnan/multiminer#11]
Please add support for this coin: https://uranium-x.com

**Comment by bogdanadnan** [comment]
I'm already working on a big refactoring which will include support for urx as well, but can't guarantee it is going to be possible. If I get good results it will be included in next release, in aprox 1-2 weeks. I'll post here a comment regarding the result when I'm done refactoring the code.

**Comment by bogdanadnan** [comment]
Support added in beta version:
https://github.com/bogdanadnan/multiminer/releases/tag/v1.1.0

**Comment by jbmustaq** [comment]
It's giving authentication error.

multiminer.exe -a argon2ad -o stratum.icemining.ca:4234 -u UNk3XYBEkNS6Q7kdH -p c=URX,worker --use-gpu CUDA --gpu-id=1,2,3,4,5,6 --gpu-batchsize=1024 -t 1

**Comment by axetota** [comment]
@jbmustaq  change "-p c=URX,worker" to "-p c=URX"

**Comment by jbmustaq** [comment]
still getting the error.

multiminer.exe -a argon2ad -o stratum+tcp://stratum.icemining.ca:4234 -u UNk3XYBEkNS6Q7kdHeoc8iqGLWfx68ZGsF -p c=URX --use-gpu CUDA --gpu-id=1 --gpu-batchsize=1024 -t 6

**Comment by jbmustaq** [comment]
Got it resolved but now I have 6 gpu and it stops at 4. and gives error " 

[Thread 0] Device #1: CUDA Device 'GeForce GTX 1060 3GB'
[Thread 1] Device #1: CUDA Device 'GeForce GTX 1060 3GB'
[Thread 2] Device #1: CUDA Device 'GeForce GTX 1060 3GB'
[Thread 3] Device #1: CUDA Device 'GeForce GTX 1060 3GB'
CUDA ERROR: out of memory
[2019-01-25 22:04:01] FAIL: thread 4 failed to initialize

**Comment by jbmustaq** [comment]
NVM got it resolved as well.

**Comment by jbmustaq** [comment]
correct config is below :-

--use-gpu CUDA --gpu-id=1,2,3,4,5,6 --gpu-batchsize=1024 -t 1
