### ISSUE TITLE
Turtlecoin new algorithm Chukwa Argon2id

### ISSUE THREAD

**Issue by angelobpool** [bogdanadnan/multiminer#18]
Hi, since Turtlecoin will fork to a new algorithm based on Argon2id, and we all crave a GPU miner, do you think your code could be used with some changes?
Here some documentation:
https://github.com/turtlecoin/turtlecoin/tree/codename_chukwa

And the CPU miner:
https://github.com/turtlecoin/trtlrig/tree/add_chukwa

There are bounty for it if you are interested

**Comment by bogdanadnan** [comment]
Created NinjaRig and added to turtlecoin github organization: https://github.com/turtlecoin/ninjarig
