### ISSUE TITLE
Multiple GPUs in same instance?

### ISSUE THREAD

**Issue by Bathmat** [bogdanadnan/multiminer#2]
Is it possible to run multiple GPUs in a single miner instance? I tried different variations for the `--gpu-id` flag, but didn't work. If not, could it be implemented in upcoming releases?

OS: Win10
GPU(s): AMD RX470/570/480/580
Driver: Adrenaline 18.5.1

EDIT: I also tried removing the `--gpu-id` flag completely, but then the miner tries to use the CPU also.

**Comment by bogdanadnan** [comment]
This has been now implemented and is in beta for testing.
https://github.com/bogdanadnan/multiminer/commit/e361b2381c868b276eb8edd018b0471f1b1bab62

**Comment by Bathmat** [comment]
Cool. Do you have Windows build/compile instructions so I can test? Or a Windows release version available?

**Comment by bogdanadnan** [comment]
Windows version can be compiled using msys2 and mingw64 toolchains as long as you disable CUDA compilation (cmake <multiminerpath> -DNO_CUDA=1). The process is similar as on Linux. For adding CUDA, the process is more complex. I will add a windows build later this week.

**Comment by bogdanadnan** [comment]
Fixed in beta:
https://github.com/bogdanadnan/multiminer/releases/tag/v1.1.0
