### ISSUE TITLE
multiminer fail to build on Gentoo

### ISSUE THREAD

**Issue by custom82** [bogdanadnan/multiminer#24]
[12/277] cd /var/tmp/portage/net-p2p/multiminer-9999/work/multiminer-9999_build/algo/argon2/argon2d/argon2-gpu/CMakeFiles/argon2-cuda.dir/lib/argon2-cuda && /usr/bin/cmake -E make_directory /var/tmp/portage/net-p2p/multiminer-9999/work/multiminer-9999_build/algo/argon2/argon2d/argon2-gpu/CMakeFiles/argon2-cuda.dir/lib/argon2-cuda/. && /usr/bin/cmake -D verbose:BOOL=OFF -D build_configuration:STRING=Gentoo -D generated_file:STRING=/var/tmp/portage/net-p2p/multiminer-9999/work/multiminer-9999_build/algo/argon2/argon2d/argon2-gpu/CMakeFiles/argon2-cuda.dir/lib/argon2-cuda/./argon2-cuda_generated_kernels.cu.o -D generated_cubin_file:STRING=/var/tmp/portage/net-p2p/multiminer-9999/work/multiminer-9999_build/algo/argon2/argon2d/argon2-gpu/CMakeFiles/argon2-cuda.dir/lib/argon2-cuda/./argon2-cuda_generated_kernels.cu.o.cubin.txt -P /var/tmp/portage/net-p2p/multiminer-9999/work/multiminer-9999_build/algo/argon2/argon2d/argon2-gpu/CMakeFiles/argon2-cuda.dir/lib/argon2-cuda/argon2-cuda_generated_kernels.cu.o.Gentoo.cmake
FAILED: algo/argon2/argon2d/argon2-gpu/CMakeFiles/argon2-cuda.dir/lib/argon2-cuda/argon2-cuda_generated_kernels.cu.o /var/tmp/portage/net-p2p/multiminer-9999/work/multiminer-9999_build/algo/argon2/argon2d/argon2-gpu/CMakeFiles/argon2-cuda.dir/lib/argon2-cuda/argon2-cuda_generated_kernels.cu.o 
cd /var/tmp/portage/net-p2p/multiminer-9999/work/multiminer-9999_build/algo/argon2/argon2d/argon2-gpu/CMakeFiles/argon2-cuda.dir/lib/argon2-cuda && /usr/bin/cmake -E make_directory /var/tmp/portage/net-p2p/multiminer-9999/work/multiminer-9999_build/algo/argon2/argon2d/argon2-gpu/CMakeFiles/argon2-cuda.dir/lib/argon2-cuda/. && /usr/bin/cmake -D verbose:BOOL=OFF -D build_configuration:STRING=Gentoo -D generated_file:STRING=/var/tmp/portage/net-p2p/multiminer-9999/work/multiminer-9999_build/algo/argon2/argon2d/argon2-gpu/CMakeFiles/argon2-cuda.dir/lib/argon2-cuda/./argon2-cuda_generated_kernels.cu.o -D generated_cubin_file:STRING=/var/tmp/portage/net-p2p/multiminer-9999/work/multiminer-9999_build/algo/argon2/argon2d/argon2-gpu/CMakeFiles/argon2-cuda.dir/lib/argon2-cuda/./argon2-cuda_generated_kernels.cu.o.cubin.txt -P /var/tmp/portage/net-p2p/multiminer-9999/work/multiminer-9999_build/algo/argon2/argon2d/argon2-gpu/CMakeFiles/argon2-cuda.dir/lib/argon2-cuda/argon2-cuda_generated_kernels.cu.o.Gentoo.cmake
nvcc fatal   : Value 'sm_30' is not defined for option 'gpu-architecture'
CMake Error at argon2-cuda_generated_kernels.cu.o.Gentoo.cmake:222 (message):
  Error generating
  /var/tmp/portage/net-p2p/multiminer-9999/work/multiminer-9999_build/algo/argon2/argon2d/argon2-gpu/CMakeFiles/argon2-cuda.dir/lib/argon2-cuda/./argon2-cuda_generated_kernels.cu.o
[multiminer-build.log](https://github.com/bogdanadnan/multiminer/files/8165022/multiminer-build.log)

**Comment by custom82** [comment]
[multiminer-build.log](https://github.com/bogdanadnan/multiminer/files/8167915/multiminer-build.log)

**Comment by custom82** [comment]
gcc 11.2.1 
nvidia-cuda-toolkit 11.6.1

**Comment by custom82** [comment]
`--- a/algo/argon2/argon2d/argon2-gpu/CMakeLists.txt     2022-03-06 18:31:55.346248635 +0100
+++ b/algo/argon2/argon2d/argon2-gpu/CMakeLists.txt     2022-03-06 18:33:22.828302947 +0100
@@ -23,7 +23,7 @@
 
 if(CUDA_FOUND)
     set(CUDA_NVCC_FLAGS ${CUDA_NVCC_FLAGS};
-        -std=c++11;--compiler-options=-fPIC;-O3;--ptxas-options=-v;-arch sm_30;-lineinfo
+        -std=c++11;--compiler-options=-fPIC;-O3;--ptxas-options=-v;-arch sm_35;-lineinfo
     )
 endif()
`

**Comment by custom82** [comment]
`--- a/algo/blake/sph-blake2s.c  2022-03-06 19:01:51.598818546 +0100
+++ b/algo/blake/sph-blake2s.c  2022-03-06 19:01:19.423167053 +0100
@@ -323,7 +323,7 @@
 
 int blake2s( uint8_t *out, const void *in, const void *key, const uint8_t outlen, const uint64_t inlen, uint8_t keylen )
 {
-       blake2s_state S[1];
+       blake2s_state S;
 
        /* Verify parameters */
        if ( NULL == in ) return -1;
@@ -334,15 +334,15 @@
 
        if( keylen > 0 )
        {
-               if( blake2s_init_key( S, outlen, key, keylen ) < 0 ) return -1;
+               if( blake2s_init_key( &S, outlen, key, keylen ) < 0 ) return -1;
        }
        else
        {
-               if( blake2s_init( S, outlen ) < 0 ) return -1;
+               if( blake2s_init( &S, outlen ) < 0 ) return -1;
        }
 
-       blake2s_update( S, ( uint8_t * )in, inlen );
-       blake2s_final( S, out, outlen );
+       blake2s_update( &S, ( uint8_t * )in, inlen );
+       blake2s_final( &S, out, outlen );
        return 0;
 }
`

**Comment by bogdanadnan** [comment]
Based on the error you might want to edit https://github.com/bogdanadnan/multiminer/blob/master/algo/argon2/argon2d/argon2-gpu/CMakeLists.txt file, line 26, and remove ;-arch sm_30 . Run cmake again and rebuild. The problem is that multiminer is old and unmaintained anymore, and recent cuda library seems to have dropped support for older architecture. It should be compilable without changes using cuda 9.
